name: printingshop
description: "A new Flutter project for Kez C-Em Zek Printing Shop"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  file_picker: ^8.1.2
  firebase_core: ^3.15.2
  firebase_storage: ^12.3.6
  url_launcher: ^6.3.0
  sqflite: ^2.3.3+1          # Local SQLite Database
  path: ^1.9.0               # Path helper para sa local DB file
  connectivity_plus: ^6.0.5  # Para ma-detect kung online o offline
  mailer: ^6.1.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true